name:  游꿛 Proponer mejoras en UI/UX
description: Proponer mejoras en la usabilidad
labels: ["游꿛 ui-ux"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripci칩n
      description: Detalla la propuesta de mejora relacionada a UI/UX.
      placeholder: |
        Por ejemplo: "Redise침o de tarjetas de stories para storylists", "Mejoras en dise침o de navbar", "Mejoras en experiencia de lectura", "Propuesta de dise침o para ordenamiento de elementos mutlimedia relacionados a stories", etc..
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Recursos
      description: Una lista de uno o m치s recursos relacionados al contenido propuesto. Se recomienda acompa침ar prototipos, wireframes o dise침os para los issues de este tipo, construidos digitalmente o dibujados a mano.
      placeholder: |
        * [Link a nuevos wireframes](https://www.recurso1.com)
        * [Link a scan para cambiar ubicaci칩n de elementos gr치ficos en vista de lectura](https://www.recurso2.com)
      validations:
        required: true
